name: Sync Tags

on:
  workflow_dispatch:

jobs:
  sync-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 全ての履歴を取得

      - name: Set up Git
        run: |
          git config user.name "NoriakiSakata-Salop"
          git config user.email "n.sakata@salop.co.jp"

      - name: Fetch upstream tags
        run: |
          git remote add upstream https://github.com/NoriakiSakata/flutter_mvvm_unit_test.git
          git fetch upstream --tags

      - name: Get latest tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)
          echo "Latest tag is: $LATEST_TAG"
          echo "latest_tag=$LATEST_TAG" >> $GITHUB_ENV

      - name: Push tags to fork
        run: |
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send notification to Slack
        uses: slackapi/slack-github-action@v1.27.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        with:
          payload: |
            {
              "text": "IMA SDK IOS 最新バージョンは ${{ env.latest_tag }} です"
            }
