name: Sync Tags

on:
  workflow_dispatch:

jobs:
  sync-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 全ての履歴を取得

      - name: Set up Git
        run: |
          git config user.name "NoriakiSakata-Salop"
          git config user.email "n.sakata@salop.co.jp"

      - name: Fetch upstream tags
        run: |
          git remote add upstream https://github.com/NoriakiSakata/flutter_mvvm_unit_test.git
          git fetch upstream --tags

      - name: Push tags to fork
        run: |
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send notification to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          args: "New tag created: ${{ github.ref }} in repository ${{ github.repository }}"
