name: Slack Notification on Tag

on:
  push:
    tags:
      - '*'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          args: "New tag created: ${{ github.ref }} in repository ${{ github.repository }}"
